/**
 * VIEWPORT
 */
export const SET_VIEWPORT = 'VIEWPORT::SET'
export const SET_VIEWPORT_ACTIVE = 'VIEWPORT::SET_ACTIVE'
export const SET_VIEWPORT_LAYOUT = 'VIEWPORT::SET_LAYOUT'
export const CLEAR_VIEWPORT = 'VIEWPORT::CLEAR'
export const SET_VIEWPORT_SPECIFIC_DATA = 'VIEWPORT::SET_VIEWPORT_SPECIFIC_DATA'
